"""Dependency-free PL/EN localization for modern and legacy HTML views."""

from __future__ import annotations

import re


# Templates inherited from the POC contain Polish text, while the settings
# view was authored in English. Phrase pairs let both render consistently and
# keep the old terminal free of client-side framework dependencies.
PHRASES: tuple[tuple[str, str], ...] = (
    ("Branding i ustawienia połączenia z Snipe-IT są stosowane natychmiast i przechowywane w wolumenie danych aplikacji.", "Branding and Snipe-IT connection settings are applied immediately and stored in the application data volume."),
    ("Najpierw połącz terminal. Po zeskanowaniu QR lub wpisaniu kodu odblokujemy wybór operacji i odbiorcy.", "Connect the terminal first. Scanning the QR or entering the code will unlock operation and recipient selection."),
    ("Zeskanuj widoczny kod QR terminalem. Po udanym parowaniu wybierzesz operację, tryb oraz odbiorcę.", "Scan the displayed QR code with the terminal. After pairing, choose the operation, mode, and recipient."),
    ("Najpierw połącz terminal kodem QR. Potem wybierz operację, tryb i odbiorcę. Aktywny terminal możesz przełączać bez ponownego parowania.", "Connect a terminal with the QR code first. Then choose the operation, mode, and recipient. You can change modes without pairing again."),
    ("Zwrot jest możliwy tylko dla przypisanego sprzętu ze statusem „Wydane” albo „Gotowy do wydania” i meta statusem „Przypisany”.", "An asset can be returned only when it is assigned, has an allowed status, and its meta status is Assigned."),
    ("Zeskanuj QR nowym terminalem. Dotychczasowy terminal pozostaje aktywny, dopóki nowe parowanie nie zakończy się poprawnie.", "Scan the QR code with the new terminal. The current terminal remains active until the new pairing succeeds."),
    ("Na MC319Z otwórz ekran parowania i użyj przycisku skanowania. Po poprawnym odczycie wrócisz do panelu, aby wybrać operację i odbiorcę.", "Open the pairing screen on the handheld and scan the code. After pairing, return to the panel to choose the operation and recipient."),
    ("Wybierz wydanie albo zwrot oraz zdecyduj, czy pracujesz pojedynczo, czy na liście urządzeń.", "Choose checkout or return and decide whether to process one asset or a batch."),
    ("Nie wybierasz osoby. Po skanie terminal pokaże, komu sprzęt jest obecnie przypisany.", "No recipient is selected. After scanning, the terminal shows the current assignee."),
    ("Wskaż nazwisko lub adres e-mail osoby, której wypożyczasz sprzęt.", "Enter the name or e-mail address of the person receiving the asset."),
    ("Zaloguj się, aby rozpocząć operację na sprzęcie", "Sign in to start an asset operation"),
    ("Podłącz ręczny skaner kodów do Snipe-IT bez udostępniania tokenu API na terminalu.", "Connect a handheld barcode scanner to Snipe-IT without exposing the API token on the terminal."),
    ("Podłącz ręczny skaner kodów do Snipe-IT i przyśpiesz wydania oraz zwroty", "Connect a handheld barcode scanner to Snipe-IT and speed up checkouts and returns"),
    ("Kod jest jednorazowy. Wygaśnie za", "The code is single-use. It expires in"),
    ("Ten QR nie zawiera operacji, odbiorcy ani danych logowania.", "This QR contains no operation, recipient, or credentials."),
    ("Skanuj kolejne urządzenia. Zatwierdzenie pojawi się po dodaniu pierwszego.", "Scan more assets. The confirmation button appears after the first item is added."),
    ("Dostęp mają wyłącznie zweryfikowane konta", "Only verified accounts in"),
    ("które istnieją również w Snipe-IT.", "that also exist in Snipe-IT are accepted."),
    ("Tylko zweryfikowane konta z", "Only verified accounts from"),
    ("Adres e-mail konta musi odpowiadać aktywnemu użytkownikowi w Snipe-IT.", "The account e-mail must match an active user in Snipe-IT."),
    ("Zaloguj przez", "Sign in with"),
    ("Lokalne logowanie administratora loginem i hasłem.", "Local administrator sign-in with username and password."),
    ("Nieudane lokalne logowanie administratora.", "Failed local administrator sign-in."),
    ("Awaryjne logowanie administratora PIN-em.", "Legacy administrator PIN sign-in."),
    ("Terminal połączony z panelem operatora.", "Terminal connected to the operator panel."),
    ("Terminal sparowany kodem QR.", "Terminal paired with a QR code."),
    ("Operator wylogował panel i zakończył sesję terminala.", "The operator signed out and ended the terminal session."),
    ("Anulowano oczekujące parowanie podczas wylogowania.", "Pending pairing was cancelled during sign-out."),
    ("Operator anulował oczekujące parowanie QR.", "The operator cancelled pending QR pairing."),
    ("Zakończono sesję z poziomu terminala.", "The session was ended from the terminal."),
    ("Odrzucono równoległe zatwierdzenie operacji.", "A concurrent operation confirmation was rejected."),
    ("Odrzucono równoległe zatwierdzenie listy.", "A concurrent batch confirmation was rejected."),
    ("Logowanie przez Google Workspace.", "Google Workspace sign-in."),
    ("Logowanie przez dostawcę tożsamości:", "Identity-provider sign-in:"),
    ("Terminal przełączony do masowego wydania dla:", "Terminal switched to batch checkout for:"),
    ("Terminal przełączony do wydania dla:", "Terminal switched to checkout for:"),
    ("Terminal przełączony do masowego zwrotu.", "Terminal switched to batch return."),
    ("Terminal przełączony do zwrotu.", "Terminal switched to return."),
    ("Terminal ustawiony do wydania dla:", "Terminal set to checkout for:"),
    ("Terminal ustawiony do zwrotu. Status docelowy:", "Terminal set to return. Target status:"),
    ("Terminal przełączony do", "Terminal switched to"),
    ("masowe wydanie", "batch checkout"),
    ("masowy zwrot", "batch return"),
    ("Logowanie PIN zablokowane limitem prób.", "PIN sign-in was blocked by the attempt limit."),
    ("Wyczyszczono listę:", "List cleared:"),
    ("Przypisano", "Checked out"),
    ("Przyjęto", "Checked in"),
    ("Terminal zastąpiony przez", "Terminal replaced by"),
    ("Nie znaleziono sprzętu dla zeskanowanego kodu.", "No asset was found for the scanned code."),
    ("Kod pasuje do", "The code matches"),
    ("urządzeń.", "assets."),
    ("Dodano", "Added"),
    ("Usunięto", "Removed"),
    ("Zakończono", "Completed"),
    ("do listy.", "to the list."),
    ("Ten sprzęt jest już na liście.", "This asset is already on the list."),
    ("Brak odbiorcy dla wydania sprzętu.", "No recipient selected for checkout."),
    ("Operacja jest już wykonywana. Poczekaj na jej zakończenie.", "The operation is already running. Wait for it to finish."),
    ("Lista sprzętu jest pusta.", "The asset list is empty."),
    ("Brak operacji do zatwierdzenia.", "There is no operation to confirm."),
    ("Token API został odrzucony przez Snipe-IT.", "The API token was rejected by Snipe-IT."),
    ("Konto API nie ma wymaganych uprawnień.", "The API account lacks the required permissions."),
    ("Nie znaleziono wybranego użytkownika.", "The selected user was not found."),
    ("Nie znaleziono sprzętu wskazanego przez kod QR.", "The asset referenced by the QR code was not found."),
    ("Kod QR wygasł albo został już użyty.", "The QR code has expired or has already been used."),
    ("Kod QR parowania wygasł albo został już użyty.", "The pairing QR code has expired or has already been used."),
    ("To nie jest kod QR parowania.", "This is not a pairing QR code."),
    ("Nieprawidłowy kod QR parowania.", "Invalid pairing QR code."),
    ("Najpierw sparuj terminal.", "Pair the terminal first."),
    ("Nie odczytano kodu.", "No code was scanned."),
    ("Aktywne parowanie terminala wygasło.", "The active terminal pairing has expired."),
    ("Brak dostępu do tej sesji terminala.", "Access to this terminal session was denied."),
    ("Dostęp jest ograniczony do domen:", "Access is restricted to domains:"),
    ("Kod parowania musi mieć sześć cyfr.", "The pairing code must contain six digits."),
    ("Kod parowania wygasł albo nie istnieje.", "The pairing code has expired or does not exist."),
    ("Kod wskazuje teraz inny sprzęt. Zeskanuj go jeszcze raz.", "The code now identifies a different asset. Scan it again."),
    ("Nie można ponownie jednoznacznie potwierdzić sprzętu. Zeskanuj go jeszcze raz.", "The asset could not be confirmed unambiguously. Scan it again."),
    ("Nie można usunąć tej pozycji.", "This item cannot be removed."),
    ("Nie można wybrać tej pozycji.", "This item cannot be selected."),
    ("Nieprawidłowa data:", "Invalid date:"),
    ("Nieprawidłowa operacja terminala.", "Invalid terminal operation."),
    ("Nieprawidłowy token formularza.", "Invalid form token."),
    ("Pozycji nie ma już na liście.", "The item is no longer on the list."),
    ("Terminal nie jest już sparowany.", "The terminal is no longer paired."),
    ("Terminal połączony. Wybierz teraz operację.", "Terminal connected. Choose an operation."),
    ("Terminal wykonuje teraz operację. Spróbuj ponownie po jej zakończeniu.", "The terminal is processing an operation. Try again after it finishes."),
    ("Tryb terminala zmienił się. Zeskanuj sprzęt ponownie.", "The terminal mode changed. Scan the asset again."),
    ("Wyczyszczono listę.", "The list was cleared."),
    ("Zbyt wiele prób. Spróbuj ponownie za", "Too many attempts. Try again in"),
    ("Blokada równoległej operacji", "Concurrent operation lock"),
    ("Nie udało się utworzyć terminala.", "The terminal could not be created."),
    ("Nie udało się wygenerować kodu parowania.", "The pairing code could not be generated."),
    ("Nieprawidłowy tryb przyjęcia sprzętu.", "Invalid asset return mode."),
    ("Nie ma aktywnego kodu QR parowania.", "There is no active pairing QR code."),
    ("Wydanie wymaga wskazania odbiorcy.", "Checkout requires a recipient."),
    ("Odbiorca zmienił się przed potwierdzeniem. Zeskanuj ponownie.", "The recipient changed before confirmation. Scan the asset again."),
    ("Dostawca tożsamości nie zwrócił prawidłowego adresu e-mail.", "The identity provider did not return a valid e-mail address."),
    ("Dostawca tożsamości nie potwierdził adresu e-mail.", "The identity provider did not verify the e-mail address."),
    ("Sprzęt nie ma zdjęcia.", "The asset has no image."),
    ("Status", "Status"),
    ("nie jest jednoznaczny w Snipe-IT.", "is ambiguous in Snipe-IT."),
    ("nie ma prawidłowego ID.", "does not have a valid ID."),
    ("Połączenie i wymagane statusy Snipe-IT są poprawne.", "The Snipe-IT connection and required statuses are valid."),
    ("Brak operacji spełniających wybrane warunki.", "No operations match the selected filters."),
    ("Wyświetlane są wyłącznie operacje wykonane przez Ciebie.", "Only operations performed by you are displayed."),
    ("Widok administratora: operacje wszystkich użytkowników.", "Administrator view: operations from all users."),
    ("Wybierz powyżej wydanie pojedyncze, masowe wydanie, zwrot pojedynczy albo masowy zwrot.", "Choose single checkout, batch checkout, single return, or batch return above."),
    ("Zaloguj przez Google Workspace", "Sign in with Google Workspace"),
    ("Logowanie Google wymaga ustawienia GOOGLE_CLIENT_ID i GOOGLE_CLIENT_SECRET.", "Google sign-in requires GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET."),
    ("Logowanie Google nie jest jeszcze skonfigurowane.", "Google sign-in is not configured yet."),
    ("Nie udało się zalogować:", "Sign-in failed:"),
    ("Ustaw ADMIN_PASSWORD w zmiennych kontenera.", "Set ADMIN_PASSWORD in the container environment."),
    ("Nieprawidłowa nazwa administratora lub hasło.", "Invalid administrator username or password."),
    ("Ustawienia zostały zapisane.", "Settings saved."),
    ("Logowanie przez dostawcę tożsamości nie jest jeszcze skonfigurowane.", "Identity-provider sign-in is not configured yet."),
    ("Logowanie przez dostawcę tożsamości wymaga adresu discovery, Client ID i Client Secret.", "Identity-provider sign-in requires a discovery URL, Client ID, and Client Secret."),
    ("Dostawca tożsamości nie zwrócił danych zalogowanego konta.", "The identity provider did not return signed-in account details."),
    ("Konto dostawcy tożsamości nie ma odpowiadającego użytkownika w Snipe-IT.", "The identity-provider account has no matching Snipe-IT user."),
    ("W Snipe-IT istnieje więcej niż jedno konto z tym adresem e-mail.", "More than one Snipe-IT account uses this e-mail address."),
    ("Adres zdjęcia nie należy do skonfigurowanego Snipe-IT.", "The image URL does not belong to the configured Snipe-IT instance."),
    ("Nie udało się pobrać zdjęcia sprzętu:", "Could not download the asset image:"),
    ("Snipe-IT nie potwierdził przypisania.", "Snipe-IT did not confirm the checkout."),
    ("Snipe-IT nie potwierdził zwrotu.", "Snipe-IT did not confirm the return."),
    ("Snipe-IT nie pozwala wydać tego sprzętu.", "Snipe-IT does not allow this asset to be checked out."),
    ("Snipe-IT nie zwrócił prawidłowego zdjęcia sprzętu.", "Snipe-IT did not return a valid asset image."),
    ("Snipe-IT zwrócił nieprawidłową odpowiedź HTTP", "Snipe-IT returned an invalid HTTP response"),
    ("Snipe-IT zwrócił HTTP", "Snipe-IT returned HTTP"),
    ("Status sprzętu nie pozwala na wydanie.", "The asset status does not allow checkout."),
    ("Zdjęcie sprzętu jest puste albo zbyt duże.", "The asset image is empty or too large."),
    ("Błąd połączenia z Snipe-IT:", "Snipe-IT connection error:"),
    ("Sprzęt jest już przypisany:", "The asset is already assigned to:"),
    ("Sprzęt jest już przypisany.", "The asset is already assigned."),
    ("Sprzęt nie jest przypisany. Nie można go przyjąć.", "The asset is not assigned and cannot be returned."),
    ("inny odbiorca", "another recipient"),
    ("brak statusu", "no status"),
    ("Nie można przyjąć sprzętu z meta statusem „brak”. Wymagany meta status: „Przypisany”.", "An asset with no meta status cannot be returned. Required meta status: “Assigned”."),
    ("Nie można przyjąć sprzętu z meta statusem „", "An asset with meta status “"),
    ("Nie można przyjąć sprzętu ze statusem „", "An asset with status “"),
    ("” lub „", "” or “"),
    ("”. Dozwolony status:", "”. Allowed status:"),
    ("”. Wymagany meta status: „Przypisany”.", "”. Required meta status: “Assigned”."),
    (", a sprzęt musi być przypisany.", ", and the asset must be assigned."),
    ("Logo jest większe niż 2 MB.", "Logo is larger than 2 MB."),
    ("Logo musi być poprawnym obrazem PNG, JPEG, GIF lub WebP.", "Logo must be a valid PNG, JPEG, GIF or WebP image."),
    ("Nieprawidłowa wartość koloru:", "Invalid color value:"),
    ("Główny kolor przycisków, aktywnych elementów i wyróżnień.", "Main color used for buttons, active controls, and highlights."),
    ("Główny kolor przycisków, aktywnych elementów, obramowań i wyróżnień.", "Main color used for buttons, active controls, borders, and highlights."),
    ("Kolor potwierdzeń, sukcesów i pozytywnych akcji.", "Color used for confirmations, success states, and positive actions."),
    ("Kolor tła nagłówka panelu operatora i terminala.", "Background color of the operator and terminal headers."),
    ("Zeskanuj listę urządzeń i zatwierdź ją jedną akcją.", "Scan a list of assets and confirm it in one action."),
    ("Zeskanuj wiele urządzeń i przyjmij całą listę.", "Scan multiple assets and return the whole list."),
    ("Wybierz odbiorcę i wydawaj po jednym urządzeniu.", "Choose a recipient and check out one asset at a time."),
    ("Zwracam sprzęt pojedynczo do magazynu.", "Return one asset at a time to inventory."),
    ("Terminal jest już połączony", "Terminal is already connected"),
    ("Połącz inny terminal", "Connect another terminal"),
    ("Połącz inny terminal kodem QR", "Connect another terminal with QR"),
    ("Połącz terminal, aby odblokować wybór operacji.", "Connect the terminal to unlock operation selection."),
    ("Połącz terminal", "Connect terminal"),
    ("Wpisz kod ręcznie", "Enter code manually"),
    ("Sprawdź kod", "Verify code"),
    ("Zeskanuj QR terminalem", "Scan QR with the terminal"),
    ("Zeskanuj QR", "Scan QR"),
    ("Sześciocyfrowy kod widoczny na terminalu", "Six-digit code shown on the terminal"),
    ("Połącz terminal z panelem operatora", "Connect the terminal to the operator panel"),
    ("Oczekiwanie na terminal…", "Waiting for terminal…"),
    ("Oczekiwanie na nowy terminal. Obecna sesja nie została przerwana.", "Waiting for the new terminal. The current session remains active."),
    ("Zeskanuj z ekranu komputera", "Scan from the computer screen"),
    ("Anuluj zmianę terminala", "Cancel terminal change"),
    ("Kontynuuj na terminalu.", "Continue on the terminal."),
    ("Lista pojawi się po wyszukaniu nazwiska lub adresu e-mail.", "Results appear after searching for a name or e-mail address."),
    ("Brak użytkowników pasujących do", "No users match"),
    ("Brak adresu e-mail", "No e-mail address"),
    ("Wybierz i rozpocznij", "Select and start"),
    ("Rozpocznij zwrot", "Start return"),
    ("Ustaw sposób przyjęcia", "Choose return method"),
    ("Status po przyjęciu", "Status after return"),
    ("Oczekujące · Wymaga serwisu", "Pending · Needs service"),
    ("Oczekujące", "Pending"),
    ("Gotowy do wydania", "Ready to deploy"),
    ("Wydanie lub zwrot sprzętu", "Asset checkout or return"),
    ("Wydanie pojedyncze", "Single checkout"),
    ("Masowe wydanie", "Batch checkout"),
    ("Zwrot pojedynczy", "Single return"),
    ("Masowy zwrot", "Batch return"),
    ("Wybierz operację", "Choose operation"),
    ("Wybierz odbiorcę", "Choose recipient"),
    ("Wyszukaj odbiorcę", "Find recipient"),
    ("Nazwisko, e-mail lub login", "Name, e-mail, or username"),
    ("Użytkownicy Snipe-IT", "Snipe-IT users"),
    ("Wybierz właściwą osobę", "Choose the correct person"),
    ("Test połączenia", "Test connection"),
    ("Przejdź do Snipe-IT", "Open Snipe-IT"),
    ("Dziennik operacji", "Operation log"),
    ("Historia działań", "Activity history"),
    ("Historia operacji", "Operation history"),
    ("Dziennik | Snipe Bridge", "Log | Snipe Bridge"),
    ("Stronicowanie dziennika", "Log pagination"),
    ("Skan:", "Scan:"),
    ("Eksport CSV", "Export CSV"),
    ("Eksport XLSX", "Export XLSX"),
    ("Od daty", "From date"),
    ("Do daty", "To date"),
    ("Wyświetlane", "Showing"),
    ("Wróć do panelu", "Back to panel"),
    ("Wyczyść filtry", "Clear filters"),
    ("Wpisów na stronę", "Rows per page"),
    ("Fragment komunikatu", "Message fragment"),
    ("Nazwa odbiorcy", "Recipient name"),
    ("Nazwa lub e-mail", "Name or e-mail"),
    ("Asset Tag lub kod skanu", "Asset Tag or scanned code"),
    ("lub kod skanu", "or scanned code"),
    ("Brak skonfigurowanego tokenu API Snipe-IT.", "The Snipe-IT API token is not configured."),
    ("Brak statusu", "Missing status"),
    ("w Snipe-IT.", "in Snipe-IT."),
    ("ZESKANUJ QR PAROWANIA", "SCAN PAIRING QR"),
    ("ALBO WPISZ KOD NA KOMPUTERZE", "OR ENTER THE CODE ON THE COMPUTER"),
    ("ID TERMINALA", "TERMINAL ID"),
    ("Wybierz wydanie lub zwrot w panelu operatora.", "Choose checkout or return in the operator panel."),
    ("TERMINAL SPAROWANY", "TERMINAL CONNECTED"),
    ("AKTUALNIE PRZYPISANO", "CURRENTLY ASSIGNED TO"),
    ("POTWIERDŹ SPRZĘT", "CONFIRM ASSET"),
    ("ZESKANUJ ZWRACANY SPRZĘT", "SCAN RETURNED ASSET"),
    ("ZESKANUJ SPRZĘT", "SCAN ASSET"),
    ("WYBIERZ DO USUNIĘCIA", "SELECT TO REMOVE"),
    ("USUNĄĆ Z LISTY?", "REMOVE FROM LIST?"),
    ("USUŃ Z LISTY", "REMOVE FROM LIST"),
    ("ZATWIERDŹ LISTĘ", "CONFIRM LIST"),
    ("WYCZYŚĆ LISTĘ", "CLEAR LIST"),
    ("ZAKOŃCZ SESJĘ", "END SESSION"),
    ("PRZEJDŹ DO PANELU OPERATORA", "OPEN OPERATOR PANEL"),
    ("WIDOK TERMINALA", "TERMINAL VIEW"),
    ("Ten ekran jest przeznaczony dla skanera ręcznego.", "This screen is intended for a handheld scanner."),
    ("PANEL OPERATORA", "OPERATOR PANEL"),
    ("Ten ekran jest przeznaczony dla komputera operatora.", "This screen is intended for the operator computer."),
    ("PRZEJDŹ DO WIDOKU TERMINALA", "OPEN TERMINAL VIEW"),
    ("PARUJ", "PAIR"),
    ("TRYB ZWROTU", "RETURN MODE"),
    ("Tryb zwrotu", "Return mode"),
    ("MASOWY ZWROT", "BATCH RETURN"),
    ("MASOWE WYDANIE", "BATCH CHECKOUT"),
    ("ODŚWIEŻ PAROWANIE", "REFRESH PAIRING"),
    ("SPRAWDŹ WYBRANY TRYB", "CHECK SELECTED MODE"),
    ("ODŚWIEŻ TRYB", "REFRESH MODE"),
    ("Numerze Seryjnym", "Serial Number"),
    ("Zielony zatwierdza, czerwony anuluje.", "Green confirms, red cancels."),
    ("Zielony usuwa, czerwony anuluje.", "Green removes, red cancels."),
    ("Enter zatwierdza aktywny przycisk.", "Enter confirms the active button."),
    ("Dopasowano po:", "Matched by:"),
    ("Dopasowano po", "Matched by"),
    ("Po zwrocie:", "After return:"),
    ("Uwagi:", "Notes:"),
    ("Nazwa:", "Name:"),
    ("Brak modelu", "No model"),
    ("Kod skanu", "Scanned code"),
    ("Wymaga serwisu", "Needs service"),
    ("Zdjęcie sprzętu", "Asset image"),
    ("PRZYPISZ", "CHECK OUT"),
    ("PRZYJMIJ", "CHECK IN"),
    ("ANULUJ", "CANCEL"),
    ("ODBIORCA", "RECIPIENT"),
    ("Odbiorca", "Recipient"),
    ("LISTA", "LIST"),
    ("Wczytywanie", "Loading"),
    ("Diagnostyka terminala", "Terminal diagnostics"),
    ("DIAGNOSTYKA TERMINALA", "TERMINAL DIAGNOSTICS"),
    ("Rozmiar i profil", "Size and profile"),
    ("Zapisano wynik w dzienniku operacji.", "Result saved in the operation log."),
    ("Linie kontrolne:", "Reference lines:"),
    ("krawędź ekranu", "screen edge"),
    ("ZAPISZ WYNIK", "SAVE RESULT"),
    ("WRÓĆ DO TERMINALA", "BACK TO TERMINAL"),
    ("Ekran", "Screen"),
    ("Profil", "Profile"),
    ("Sukces", "Success"),
    ("Duplikat", "Duplicate"),
    ("Ostrzeżenie", "Warning"),
    ("Zablokowano", "Blocked"),
    ("Niejednoznaczny", "Ambiguous"),
    ("Nie znaleziono", "Not found"),
    ("Błąd", "Error"),
    ("Wszystkie", "All"),
    ("Filtruj", "Filter"),
    ("Poprzednia", "Previous"),
    ("Następna", "Next"),
    ("Strona", "Page"),
    ("Czas", "Time"),
    ("Wynik", "Result"),
    ("Operacja", "Operation"),
    ("Sprzęt", "Asset"),
    ("Komunikat", "Message"),
    ("E-mail operatora", "Operator e-mail"),
    ("Snipe ID operatora", "Operator Snipe ID"),
    ("ID terminala", "Terminal ID"),
    ("Logowanie", "Sign-in"),
    ("Parowanie QR", "QR pairing"),
    ("Parowanie ręczne", "Manual pairing"),
    ("Parowanie terminala", "Terminal pairing"),
    ("Parowanie", "Pairing"),
    ("Jednorazowy kod QR parowania terminala", "Single-use terminal pairing QR code"),
    ("Zeskanuj ten QR terminalem", "Scan this QR code with the terminal"),
    ("Kod wygaśnie za", "The code expires in"),
    ("s i może zostać użyty tylko raz.", "s and can be used only once."),
    ("Anuluj parowanie", "Cancel pairing"),
    ("Anulowanie parowania", "Pairing cancelled"),
    ("Terminal sparowany. Przechodzę do panelu…", "Terminal paired. Opening the operator panel…"),
    ("Kod wygasł. Wróć do panelu i przygotuj nowy.", "The code has expired. Return to the panel and generate a new one."),
    ("Połącz kodem ręcznym", "Connect with a manual code"),
    ("Zmiana terminala", "Terminal change"),
    ("Zmiana trybu", "Mode change"),
    ("Wylogowanie operatora", "Operator sign-out"),
    ("Zakończenie sesji terminala", "Terminal session ended"),
    ("Wyszukanie sprzętu", "Asset lookup"),
    ("Dodanie do listy", "Added to list"),
    ("Usunięcie z listy", "Removed from list"),
    ("Wyczyszczenie listy", "List cleared"),
    ("Wydanie", "Checkout"),
    ("Zwrot", "Return"),
    ("Logowanie administratora", "Administrator sign-in"),
    ("Nazwa użytkownika", "Username"),
    ("Hasło", "Password"),
    ("Zaloguj", "Sign in"),
    ("Wyloguj", "Sign out"),
    ("Ustawienia", "Settings"),
    ("Panel operatora", "Operator panel"),
    ("Dostęp operatora", "Operator access"),
    ("Szukaj", "Search"),
    ("Krok 1", "Step 1"),
    ("Krok 2", "Step 2"),
    ("Krok 3", "Step 3"),
    ("Administracja", "Administration"),
    ("Ustawienia aplikacji", "Application settings"),
    ("Branding, Snipe-IT i ustawienia dostawcy tożsamości są przechowywane w wolumenie danych aplikacji i stosowane natychmiast.", "Branding, Snipe-IT, and identity provider settings are stored in the application data volume and applied immediately."),
    ("Wróć do panelu operatora", "Back to operator panel"),
    ("Marka", "Branding"),
    ("Tożsamość i język", "Identity and language"),
    ("Nazwa aplikacji", "Application name"),
    ("Krótki tytuł terminala", "Short terminal title"),
    ("Nazwa organizacji", "Organization name"),
    ("Język interfejsu", "Interface language"),
    ("Pokaż opis na stronie logowania", "Show description on the sign-in page"),
    ("Opis logowania po polsku", "Sign-in description in Polish"),
    ("Opis logowania po angielsku", "Sign-in description in English"),
    ("Opis na stronie logowania", "Sign-in page description"),
    ("Logo (PNG, JPEG, GIF lub WebP; maks. 2 MB)", "Logo (PNG, JPEG, GIF or WebP; max. 2 MB)"),
    ("Integracja", "Integration"),
    ("Adres bazowy", "Base URL"),
    ("Token API", "API token"),
    ("Usuń zapisany token API", "Remove stored API token"),
    ("Dodatkowe pole sprzętu", "Additional asset field"),
    ("Status wydania", "Checkout status"),
    ("Status gotowości", "Ready status"),
    ("Status serwisowy", "Service status"),
    ("Domena Google Workspace", "Google Workspace domain"),
    ("Dostawca tożsamości", "Identity provider"),
    ("Uwierzytelnianie", "Authentication"),
    ("Dostawca", "Provider"),
    ("Wyświetlana nazwa dostawcy", "Provider display name"),
    ("Adres discovery OpenID Connect", "OpenID Connect discovery URL"),
    ("Sekret klienta", "Client secret"),
    ("Usuń zapisany sekret klienta", "Remove stored client secret"),
    ("Pokaż ostrzeżenie o konfiguracji dostawcy tożsamości na stronie logowania", "Show the identity-provider configuration warning on the sign-in page"),
    ("Adres przekierowania", "Redirect URL"),
    ("Kopiuj", "Copy"),
    ("Dozwolone domeny tożsamości", "Allowed identity domain(s)"),
    ("Zakresy OIDC", "OIDC scopes"),
    ("Claim adresu e-mail", "E-mail claim"),
    ("Claim grup", "Groups claim"),
    ("Grupy administratorów", "Administrator groups"),
    ("Zarejestruj", "Register"),
    ("jako dozwolony adres callback u dostawcy.", "as an allowed callback URL at the provider."),
    ("Opcjonalne ograniczenie po stronie aplikacji na podstawie claimu e-mail. Oddziel wiele domen przecinkami; pozostaw puste, aby dopuścić wszystkie domeny.", "Optional application-side restriction based on the e-mail claim. Separate multiple domains with commas; leave blank to allow every domain."),
    ("Członkowie tych grup dostawcy tożsamości otrzymują uprawnienia administratora. ADMIN_EMAILS i lokalne logowanie administratora nadal są obsługiwane.", "Members of these identity-provider groups receive administrator access. ADMIN_EMAILS and local administrator login remain supported."),
    ("Odśwież listę statusów", "Refresh status list"),
    ("Odświeżono listę statusów Snipe-IT:", "Refreshed the Snipe-IT status list:"),
    ("Snipe-IT zwrócił pustą listę statusów. Zachowano bieżące wartości.", "Snipe-IT returned an empty status list. Existing values were kept."),
    ("Nie udało się odświeżyć listy statusów:", "Could not refresh the status list:"),
    ("Nie udało się pobrać statusów Snipe-IT:", "Could not download Snipe-IT statuses:"),
    ("Bieżące wartości pozostają dostępne.", "Current values remain available."),
    ("niedostępny", "unavailable"),
    ("Zapisz ustawienia", "Save settings"),
    ("Główny", "Primary"),
    ("Akcent", "Accent"),
    ("Nagłówek", "Header"),
)


def localize_html(html: str, language: str) -> str:
    language = language.strip().lower()
    if language not in {"pl", "en"}:
        language = "en"
    protected: list[str] = []
    pattern = re.compile(
        r"<(span|textarea)\b[^>]*\bdata-no-localize\b[^>]*>.*?</\1>"
        r"|<input\b[^>]*\bdata-no-localize\b[^>]*>"
        r"|<option\b[^>]*>",
        re.IGNORECASE | re.DOTALL,
    )

    def protect(match: re.Match[str]) -> str:
        protected.append(match.group(0))
        # Private-use delimiters are non-word characters. Unlike the former
        # underscore token, they do not break a phrase boundary immediately
        # after a protected opening tag (most visibly inside <option>).
        return f"\ue000P{len(protected) - 1}\ue001"

    html = pattern.sub(protect, html)
    # These Snipe-IT field names are product terms and must never be translated.
    for invariant in ("UAM Asset Tag", "Asset Tag"):
        if invariant in html:
            protected.append(invariant)
            html = html.replace(
                invariant, f"\ue000P{len(protected) - 1}\ue001"
            )
    pairs = PHRASES if language == "en" else tuple((en, pl) for pl, en in PHRASES)
    replacements = sorted(pairs, key=lambda item: len(item[0]), reverse=True)
    tokens: list[tuple[str, str]] = []
    for index, (source, target) in enumerate(replacements):
        token = f"\ue000T{index}\ue001"
        phrase_pattern = re.escape(source)
        if source and source[0].isalnum():
            phrase_pattern = r"(?<!\w)" + phrase_pattern
        if source and source[-1].isalnum():
            phrase_pattern = phrase_pattern + r"(?!\w)"
        html, count = re.subn(phrase_pattern, token, html)
        if count:
            tokens.append((token, target))
    for token, target in tokens:
        html = html.replace(token, target)
    if language == "en":
        html = re.sub(r"(Page\s+\d+)\s+z\s+(\d+)", r"\1 of \2", html)
        html = re.sub(r"(\d+)\s+wpis(?:ów|y)", r"\1 entries", html)
        html = re.sub(
            r"(?<!\w)(\d+)\s+SZT\.",
            lambda match: f"{match.group(1)} "
            + ("ITEM" if match.group(1) == "1" else "ITEMS"),
            html,
        )
        html = re.sub(
            r"(?<!\w)(\d+)\s+szt\.",
            lambda match: f"{match.group(1)} "
            + ("item" if match.group(1) == "1" else "items"),
            html,
        )
    else:
        html = re.sub(r"(?<!\w)(\d+)\s+ITEMS?", r"\1 SZT.", html)
        html = re.sub(r"(?<!\w)(\d+)\s+items?", r"\1 szt.", html)
    for index, value in enumerate(protected):
        html = html.replace(f"\ue000P{index}\ue001", value)
    return html
